name: Generate Method-Test Mapping from CSVs

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-mapping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Run mapping script
        run: python3 app/reverse_map.py

      - name: Upload method_test_mapping.json
        uses: actions/upload-artifact@v4
        with:
          name: method_test_mapping
          path: app/target/method_test_mapping.json
