name: Reverse Coverage Mapping 333e35

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  reverse-mapping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Extract test method names
        run: |
         mkdir -p test-list
         grep -r "@Test" app/src/test/java > temp.txt || true
         grep -Po '(?<=void )\w+' temp.txt > test-list/tests.txt || true
         rm -f temp.txt
         echo "Detected tests:"
         cat test-list/tests.txt || true


      - name: Run tests one by one to capture per-test JaCoCo exec files
        run: |
          mkdir -p test-execs
          while read testName; do
            echo "Running test: $testName"
            rm -f app/target/jacoco.exec   # Clear previous coverage
            mvn -pl app -Dtest="**.*#$testName" test
            cp app/target/jacoco.exec "test-execs/$testName.exec"
          done < test-list/tests.txt

      - name: Install JaCoCo CLI
        run: |
          mkdir jacococli
          curl -L -o jacococli.zip https://repo1.maven.org/maven2/org/jacoco/jacoco/0.8.11/jacoco-0.8.11.zip
          unzip -j jacococli.zip '*/lib/jacococli.jar' -d jacococli

      - name: Generate reverse mapping XMLs
        run: |
          mkdir -p reverse-mapping
          for execFile in test-execs/*.exec; do
            testName=$(basename "$execFile" .exec)
            java -jar jacococli/jacococli.jar report "$execFile" \
              --classfiles app/target/classes \
              --sourcefiles app/src/main/java \
              --xml "reverse-mapping/$testName.xml"
          done

      - name: Run Python script to build mapping
        run: |
          python3 reverse_map.py

      - name: Upload reverse mapping artifact
        uses: actions/upload-artifact@v4
        with:
          name: method_test_mapping
          path: reverse-mapping/method_test_mapping.json
